language: cpp

compiler:
  - clang
  - gcc

os:
  - linux

dist: xenial

addons:
  apt:
    update: true
    packages:
      - libboost-all-dev
      - doxygen
      - flex
      - bison
      - help2man
      - graphviz

  homebrew:
    packages:
      - boost
      - doxygen
      - flex
      - bison
      - help2man
      - graphviz
    update: true

before_install: autoreconf -fi

script: ./configure && make && make check
