language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

dist: xenial

addons:
  apt:
    packages:
      - libboost-regex-dev
      - doxygen
      - flex
      - bison
      - help2man
      - graphviz
    update: true

  homebrew:
    packages:
      - boost
      - doxygen
      - flex
      - bison
      - help2man
      - graphviz
    update: true

before_install: autoreconf -fi

script: ./configure && make -j && make -j distcheck
