language: cpp

os:
  - linux

dist: trusty

sudo: false


matrix:
  include:
    ##########################################################################
    # Build with the main configuration on all the supported compilers
    ##########################################################################
    # Clang 3.5
    - env: UNIT_TESTS=true COMPILER=clang++-3.5 BOOST_VERSION=default ENABLE_MEMCHECK=true




install:
  ############################################################################
  # All the dependencies are installed in ${HOME}/deps/
  ############################################################################
  - DEPS_DIR="${HOME}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}



before_script:
  ############################################################################
  # Go back to the root of the project and setup the build directory
  ############################################################################
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - echo "${CONFIG_OPTIONS}"
