language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

dist: xenial

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - boost1.67
      - doxygen
      - flex
      - bison
      - help2man
      - graphviz

  homebrew:
    packages:
      - boost
      - doxygen
      - flex
      - bison
      - help2man
      - graphviz
    update: true

before_install: autoreconf -fi

script: ./configure && make -j && make -j distcheck
